### ISSUE TITLE
Disable multiselectable not working

### ISSUE THREAD

**Issue by tonykim5** [nico3333fr/jquery-accessible-accordion-aria#16]
Disabling the multiselectable feature doesn't seem to work. Pasted the HTML from my site's page source. I'm using v2.2.1.

`<div class="js-accordion faq-accordian" data-accordion-multiselectable="none" data-accordion-prefix-classes="faq-accordian" role="tablist" aria-multiselectable="true">`

**Comment by nico3333fr** [comment]
Hi @tonykim5 

you are right, this was a bug, I've fixed it in the last commit : https://github.com/nico3333fr/jquery-accessible-accordion-aria/commit/4359a9ce294de82b707294cf7716715f70f9217d

Thanks a lot for reporting it ;)

**Comment by tonykim5** [comment]
Hey Nicolas, thanks for the quick response but the updated version doesn't seem to be working still. I made sure the old version wasn't being cached in my browser.

**Comment by nico3333fr** [comment]
Hi @tonykim5 this is strange, it works for me, see example here https://a11y.nicolas-hoffmann.net/accordion/?nomultiselect=1

**Comment by tonykim5** [comment]
Yes I got it to work now. Thanks Nicolas! Great set of accessible plugins.

**Comment by nico3333fr** [comment]
Great, happy to hear it is ok ! 👍
