### ISSUE TITLE
Incorrect selector for keydown event handler

### ISSUE THREAD

**Issue by swissspidy** [nico3333fr/jquery-accessible-accordion-aria#17]
Inside `Accordion.prototype.initEvents`, the selector being used is `this.options.panelSelector`.

However, the correct one would be `this.options.panelsSelector` (`panels` vs. `panel`).

See https://github.com/nico3333fr/jquery-accessible-accordion-aria/blob/1a3c71a2d218156fea7730840d37c007b9687b71/jquery-accessible-accordion-aria.js#L21 and https://github.com/nico3333fr/jquery-accessible-accordion-aria/blob/1a3c71a2d218156fea7730840d37c007b9687b71/jquery-accessible-accordion-aria.js#L107

**Comment by nico3333fr** [comment]
Correct, this is fixed, and this allowed me to find another bug.

Thank you 👍
