### ISSUE TITLE
Allow setting multiselectable via options

### ISSUE THREAD

**Issue by swissspidy** [nico3333fr/jquery-accessible-accordion-aria#18]
If you pass `multiselectable` as an option like any other, its value gets overridden by `specificOptions.multiselectable` (the `data-accordion-multiselectable`) attribute.

I think it makes sense to not override it as long as no data attribute is present, e.g. when I use `$( '$( '.foobar' ).accordion( { multiselectable: false } );`, I expect `multiselectable` to be false.

**Comment by nico3333fr** [comment]
You are right, it is fixed now.

Thanks for pointing this out 👍
