### ISSUE TITLE
Only open one panel at a time.

### ISSUE THREAD

**Issue by CGTS** [nico3333fr/jquery-accessible-accordion-aria#2]
Is there a way to allow only one panel at a time? Also I've noticed when I call a page in a page dynamically, leave and then return the accordion requires multiple clicks to open/close.

Any ideas?

**Comment by nico3333fr** [comment]
Hi,

yes, I'm working on it, it should be added in a few days as a parameter. :)

Nicolas

**Comment by nico3333fr** [comment]
Hi @CGTS , the last update has added an option to have only one panel opened at the same time ;)
