### ISSUE TITLE
data-accordion-opened="true" - mistake in documentation

### ISSUE THREAD

**Issue by dariodev** [nico3333fr/jquery-accessible-accordion-aria#24]
Hi, I found a small mistake in documentation. It is stated that if want to have an accordion content opened by default, we should add the attribute data-accordion-opened="true" on a hx, but should be added on a div (panel).
Thanks for a great plugin - fantastique!

**Comment by nico3333fr** [comment]
Hi,

you're right, this is a mistake. I'm going to fix it asap...

**Comment by nico3333fr** [comment]
Hi @dariodev 

it is fixed, thanks a lot for reporting this mistake. 👍
