### ISSUE TITLE
Problème de génération de balise dans accordéon (JS)

### ISSUE THREAD

**Issue by hemoreau** [nico3333fr/jquery-accessible-accordion-aria#26]
Bonjour, 
Je suis face à un problème de génération de code avec votre code concernant l'accordéon.

**Problème actuellement ->** 
Code de base : 
```
<h2 class="js-accordion__header article-title">Titre de la partie 1
        <span class="open">Ouvrir</span>
        <span class="close" >Fermer</span>
</h2>
```

Code généré : 
```
<button id="accordion-0-0_tab" class="js-accordion__header block-accordion__header" type="button" aria-controls="accordion-0-0" aria-expanded="true" role="tab" aria-selected="true">
         Titre de la partie 1 Ouvrir Fermer 
</button>
```

**Demande de solution ->** 
Est-il possible de garder les balises présentes dans le h2 lorsque l'on génère le button ?
Exemple de code généré : 
```
<button id="accordion-0-0_tab" class="js-accordion__header block-accordion__header" type="button" aria-controls="accordion-0-0" aria-expanded="true" role="tab" aria-selected="true">
         Titre de la partie 1 
        <span class="open">Ouvrir</span>
        <span class="close" >Fermer</span> 
</button>
```

Merci

**Comment by juliemoynat** [comment]
Hello @nico3333fr, je plussoie ce besoin ;-) J'espère qu'il y a une solution toute bête pour ça. :)

**Comment by nico3333fr** [comment]
Il y a des solutions (reprendre le contenu html au lieu du texte), je vais essayer d'y travailler dès que possible.

Merci pour la suggestion ;)

**Comment by nico3333fr** [comment]
Hello vous deux,

l'option a été ajoutée dans https://github.com/nico3333fr/jquery-accessible-accordion-aria/commit/1607dbfe447fbae053d7a3f1dd17085b8152f022 .

La doc est à jour sur https://a11y.nicolas-hoffmann.net/accordion/ (et dans le Readme avec un exemple spécial ;) https://github.com/nico3333fr/jquery-accessible-accordion-aria/blob/master/README.md#all-options-of-the-plugin )

Merci et bonne fin de week-end ;)
