### ISSUE TITLE
Nested accordions have some troubles with focus management

### ISSUE THREAD

**Issue by nico3333fr** [nico3333fr/jquery-accessible-accordion-aria#27]
Issue reproductible here: https://codepen.io/nico3333fr/pen/QMxaqq

**Comment by ryuran** [comment]
I see, but how it should works?
I want to try to write  some test to check the good behavior…

**Comment by nico3333fr** [comment]
Fixed with https://github.com/nico3333fr/jquery-accessible-accordion-aria/commit/33d1d52c9aa1f927aac34bc6a25f9b6c05e24b15
