### ISSUE TITLE
please update bower with current tag

### ISSUE THREAD

**Issue by zzramesses** [nico3333fr/jquery-accessible-accordion-aria#32]
Bower is still showing a tag of 2.5.1 while the version here is 2.6.  Can you please update so I can user bower to update my local version.  https://libraries.io/bower/jquery-accessible-accordion-aria

**Comment by nico3333fr** [comment]
This is strange, the bower file has 2.6.0 as version specified (?!).

**Comment by zzramesses** [comment]
I saw that too. I’m not sure how to let bower know.

**Comment by nico3333fr** [comment]
Sorry for delay (really too busy): it is fixed via https://github.com/nico3333fr/jquery-accessible-accordion-aria/commit/f526a457179834392375cc313bbcafff6f335cbf
