### ISSUE TITLE
Unspecified method keydownPanelEventHandler ?

### ISSUE THREAD

**Issue by anthonybertossi** [nico3333fr/jquery-accessible-accordion-aria#35]
There is an error or a typo ? 
I don't find the implementation of the method keydownPanelEventHandler who is called in `Accordion.prototype.initEvents()`
`this.$wrapper.on('keydown', this.options.panelsSelector, $.proxy(this.keydownPanelEventHandler, this));`

**Comment by mosne** [comment]
great putting in comment `   // this.$wrapper.on('keydown', this.options.buttonsSelector, $.proxy(this.keydownButtonEventHandler, this));

    //  this.$wrapper.on('keydown', this.options.panelsSelector, $.proxy(this.keydownPanelEventHandler, this));
` solved the issue with jquery 3.x

**Comment by nico3333fr** [comment]
Sorry for delay (really too busy): it is fixed via https://github.com/nico3333fr/jquery-accessible-accordion-aria/commit/f526a457179834392375cc313bbcafff6f335cbf
