### ISSUE TITLE
Make a real Module with init and setting

### ISSUE THREAD

**Issue by ryuran** [nico3333fr/jquery-accessible-accordion-aria#9]
Currently it is impossible to :
- change class `accordion`.
- init or destroy (enable/disabled) separately several accordion (2 accordion in page but init and destroy separately in function of media queries)
- impossible to set settings in js (only data-attribute : It will repeat a lot of html if all accordions do not use default settings)
- catch event (event are not named, so impossible to catch event from accordion for stat or synchro)

**Comment by ryuran** [comment]
see #10

**Comment by nico3333fr** [comment]
Perfect, it is merged. Thanks a lot :)
